CREATE DATABASE DB_GENERATION_GAME;
USE DB_GENERATION_GAME;

CREATE TABLE TB_CLASSES(
	ID BIGINT(5) AUTO_INCREMENT,
    MAGO VARCHAR(255),
    GUERREIRO VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGEM (
	ID BIGINT(5) AUTO_INCREMENT,
    ATAQUE DECIMAL(6,2) NOT NULL,    
    DEFESA DECIMAL(6,2) NOT NULL,
    HP BIGINT(5),
    MP BIGINT(5),
    CATEGORIA_ID BIGINT,
	PRIMARY KEY(ID),
    FOREIGN KEY(CATEGORIA_ID) REFERENCES TB_CLASSES(ID)
);

INSERT INTO TB_CLASSES(MAGO)
	VALUES("Ilusionista");

INSERT INTO TB_CLASSES(MAGO)
	VALUES("Alquimista");

INSERT INTO TB_CLASSES(GUERREIRO)
	VALUES("Arcano");

INSERT INTO TB_CLASSES(GUERREIRO)
	VALUES("Combatente");

INSERT INTO TB_PERSONAGEM(ATAQUE,DEFESA,HP,MP,CATEGORIA_ID)
	VALUES(2500.00,240.25,90,350,1);    
	
INSERT INTO TB_PERSONAGEM(ATAQUE, DEFESA,HP,MP,CATEGORIA_ID)
	VALUES(5800.00,340.200,150,90,2);     

