CREATE DATABASE db_pizzaria_legal;

USE db_pizzaria_legal;

CREATE TABLE tb_categorias(
	ID BIGINT(5) AUTO_INCREMENT,
    BORDA VARCHAR(255) NOT NULL,
	SABOR VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE tb_pizzas(
	ID BIGINT(5) AUTO_INCREMENT,
    NOME VARCHAR(255),
    CODPIZZA VARCHAR(255),
    PRECO DECIMAL(6,2),
    TAMANHO VARCHAR(255),  
    CATEGORIA_ID BIGINT,
	PRIMARY KEY(ID),
    FOREIGN KEY(CATEGORIA_ID) REFERENCES tb_categorias(ID)
);

INSERT INTO tb_categorias(BORDA, SABOR)
	VALUES("Borda Recheada", "Salgada");

INSERT INTO tb_categorias(BORDA, SABOR)
	VALUES("Borda Não Recheada", "Salgada");
    
INSERT INTO tb_categorias(BORDA, SABOR)
	VALUES("Borda Recheada", "Doce");

INSERT INTO tb_categorias(BORDA, SABOR)
	VALUES("Borda Não Recheada", "Doce");

INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Margheritta","AZ200",55.00,"Média",1);
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Palmito","AZ201",50.00,"Grande");    
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Doce de Leite","AZ202",60.00,"Média",4);
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Nutella","AZ203",52.50,"Grande",3);
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Portuguesa","AZ204",55.00,"Média",2); 
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Calabresa","AZ205",53.50,"Média",1);    
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Pepperoni","AZ206",65.00,"Grande",1);
    
INSERT INTO tb_pizzas(NOME,CODPIZZA,PRECO,TAMANHO, CATEGORIA_ID)
	VALUES("Quatro Queijos","AZ207",58.50,"Pequena",2);  
    
SELECT * FROM tb_pizzas WHERE PRECO > 45;

SELECT * FROM tb_pizzas WHERE PRECO > 50 AND PRECO < 100;

SELECT * FROM tb_pizzas WHERE NOME LIKE "M%";

SELECT * FROM tb_pizzas INNER JOIN tb_categorias ON
tb_pizzas.CATEGORIA_ID = tb_categorias.ID;